local default_rules = {
	{
		keys = { "<Up>", "<Down>", "<Left>", "<Right>" },
		message = "HJKL disciple! Use proper vim motions!",
		icon = "🔄",
		threshold = 3,
		timeout = 1000,
	},
	{
		mode = "v",
		keys = { "h", "j", "k", "l" },
		message = "Use text objects instead!",
		icon = "👀",
		threshold = 8,
	},
	{
		mode = "v",
		keys = { "h", "j", "k", "l" },
		message = "Use text objects instead!",
		icon = "👀",
		threshold = 8,
	},
	{
		mode = "c",
		keys = { "<Up>", "<Down>" },
		message = "Try command history completion (q:) instead!",
		icon = "⌨️",
		threshold = 3,
	},
	{
		keys = { ":Git ", ":Gpush", ":Gpull" },
		message = "Maybe try a proper Git client?",
		icon = "🌪️",
		threshold = 4,
		timeout = 5000,
		mode = "c",
	},
	{
		keys = { "v", "V", "<C-v>" },
		message = "Most operations don't need visual mode!",
		icon = "👀",
		threshold = 8,
		timeout = 3000,
	},
	{
		keys = { "v", "V", "<C-v>" },
		message = "Most operations don't need visual mode!",
		icon = "👀",
		threshold = 8,
		timeout = 3000,
	},
	{
		keys = { "i", "I", "a", "A", "o", "O" },
		message = "Insert mode is a privilege, not a right!",
		icon = "⏳",
		threshold = 8,
		timeout = 3000,
	},
	{
		keys = { "<leader>w", ":w<CR>" },
		message = "Autosave is already handling this! Chill!",
		icon = "💾",
		threshold = 5,
		timeout = 5000,
	},
	{
		keys = { "<LeftMouse>", "<RightMouse>", "<ScrollWheelUp>", "<ScrollWheelDown>" },
		message = "You're better than this! Use keyboard!",
		icon = "🐭",
		threshold = 2,
	},
	{
		keys = { "<Esc>" },
		message = "Try `jk` or `Ctrl-[` instead!",
		icon = "🚪",
		threshold = 5,
		timeout = 2000,
	},
	{
		keys = { "n", "N" },
		message = "Maybe try improving your search pattern?",
		icon = "🔎",
		threshold = 10,
		timeout = 1500,
	},
	{
		keys = { "x", "X" },
		message = "Real vimmers use `d` motions!",
		icon = "🗑️",
		threshold = 5,
	},
	{
		keys = { ":q<CR>", ":q!<CR>" },
		message = "ZZ/ZQ are quicker!",
		icon = "🚫",
		threshold = 3,
	},
}

return default_rules
